import type { Metadata } from "next";
import { Inter, Anton, Montserrat } from "next/font/google";
import { ReactLenis } from "@/lib/lenis";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis options={{ lerp: 0.2 }} root>
        <body
          className={`${inter.className} ${anton.variable} ${montserrat.variable}`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
